import time
import sys
import os

user = os.getlogin()
print("-_-\x1B[3mDescription Maker\x1B[0m-_-")
print(" -_-\x1B[3mMade by gu10b\x1B[0m-_- ")
print(" ")
print("More projects at:")
print("https://github.com/gu10bby?tab=repositories")
print("")
var1 = input("Ready? ")
if var1 == ("yes"):
    print(" Ok, let's go.")
if var1 == ("no"):
    print(" Ok. :/")
    sys.exit()
time.sleep(2)
print("")
print("")
print("")
print("")
print("*walks in*")
time.sleep(1.25)
print("*notices you*")
time.sleep(1.25)
print("*walks into you*")
time.sleep(1.5)
print("")
print("gu10b: Hi " + user + "!")
time.sleep(1.5)
print("gu10b: Can you help me on something?")
time.sleep(1.5)
print(user + ": Yeah...?")
time.sleep(1.5)
print("gu10b: Ok, you gotta answer my questions.")
time.sleep(1.6)
print(user + ": Alright, i guess...")
time.sleep(2.20)
print("")
print("")
name = input("What is your entire name, " + user + "? ")
time.sleep(1.25)
print("gu10b: What a nice name!")
time.sleep(0.75)
age = input("What is your age? ")
time.sleep(0.75)
work = input("What is your job? ")
time.sleep(0.75)
print("gu10b: Alright! Just give me some seconds.")
time.sleep(3)
print("")
print("")
print("gu10b: Can i show you my text?")
time.sleep(1.6)
print(user + ": Sure i guess!")
time.sleep(1.5)
print("gu10b: Alright!")
time.sleep(1.5)
print("")
print("")
print("Hello! I'm " + name + " and i'm " + age + " old.")
print("I'm currently a " + work + "and yeah! I hope you enjoyed this python project!")
print("(make sure to sub to my channel! t.ly/sub2gu10b)")
print("-gu10b ;)")
